config/routes.rb
Rails.application.routes.draw do

resources :sessions, only: [:new, :index, :destroy]

resources :users #, only: [:new, :index, :create, :show]

root "home#index"

resources :specials, :bars, :users

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'bars/new' => 'bars#new'
  resources :bars do
    resources :specials
  end

get '/bars/:bar_id/specials/:id' => 'specials#show'
get '/bars/:bar_id/specials' => 'specials#create'

  get 'bars/index'

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_many :specials

  accepts_nested_attributes_for :specials,
  :allow_destroy => true,
  :reject_if => :all_blank

  geocoded_by :address
  after_validation :geocode 
end

app/models/special.rb
class Special < ActiveRecord::Base
  belongs_to :bar
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  validates :user_name, presence: true, length: {maximum: 50},
                      uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 3 }, allow_nil: true

# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  #simple coding by ip_address > http://www.rubygeocoder.com/
  geocoded_by :ip_address,
  :latitude => :lat, :longitude => :lon
after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
      redirect_to login
    end
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :set_bar, only: [:show, :edit, :update]
  before_action :admin_user,     only: :destroy

  # get/bars
  def index
    @bars = Bar.paginate(page: params[:page])
    @hash = Gmaps4rails.build_markers(@bars) do |bar, marker|
      marker.lat bar.latitude
      marker.lng bar.longitude
      marker.infowindow bar.bar_name
      marker.picture( {
        "url": "http://i.imgur.com/dNVi4Xq.png",
        "width":  32,
        "height": 32})
    end
  end

# post/bars
  def create
    @bar = Bar.new bar_params
    if @bar.save
      flash[:success] = ('Bar was added to Pau Hana Chi!')
      redirect_to bars_path
      else
        render :new
    end
  end

  # get/bar/new
  def new
    @bar = Bar.new
    3.times { @bar.specials.build}
  end

  # get/bars/id/edit
  def edit
    @bar = current_bar
  end

  # get/bars/id
  def show
    @bar = Bar.find(params[:id])
    @specials = current_bar.specials
  end

# patch/put/bars/1
  def update
    @bar = current_bar
    @specials =current_bar.specials
    if @bar.update_attributes(bar_params)


      flash[:success] = "Bar updated"
      redirect_to @bar
    else
      render 'edit'
  end
end
# delete/bars/id
  def destroy
    @bar = current_bar
    @bar.destroy
    flash[:success] = "Bar Deleted"
    redirect_to bars_path
  end

#bars latitude and longitude
  def bar_lat_long
    @barslatlong = [params[:latitude],params[:longitude]].join(",")
  end




private

  def set_bar
    @bar = Bar.find(params[:id])
  end

  def current_bar
    @current_bar || Bar.find(params[:id]) if params[:id]
  end

  def bar_params
    params.require(:bar).permit(:bar_name, :address, :city, :zipcode, :neighborhood, :phone, :website, :latitude, :longitude, specials_attributes:[:special_id, :special_description, :day, :special_price, :start_time, :end_time])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end #the real end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect to the user's show page.
        log_in user
        redirect_to root_url
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
  end

  def destroy
      log_out
      flash[:success] = "Come back soon!"
      redirect_to root_url
  end

end #the real end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController

before_action :admin_user,     only: [:destroy, :edit]
#get/specials
  def index
    @specials = Special.all
  end
# post/Specials
  def create
    @bar = Bar.find(params[:bar_id])
    @special = @bar.specials.build

    if @special.save
      flash[:success] = ["Special was added "]
      redirect_to bar_path
        else
        render :new
      end
    end

#get/special/new
  def new
    @bar = Bar.find(params[:bar_id])
    @special = @bar.specials.build
  end

  def edit
    @special = current_special
  end

  def show

    @special = current_special

  end

  def update
    @special =current_special
    if @special.update_attributes(params[:special])
      flash[:success] = "Special Updated"
      redirect_to @bar
    else
      render 'edit'
  end
end

  def destroy
    @special_price = current_special
    @special.destroy
    flash[:success] = "Special deleted"
    redirect_to bar_path
  end


private


  def current_special
    @current_special || Special.find(params[:id]) if params[:id]

  end

  def special_params
    params.require(:special).permit(:special_description, :day, :special_price, :start_time, :end_time)

  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end # the real end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Pau Hana Chi"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
      session.delete(:user_id)
      @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/bars/_bar.html.erb
<li>
<%= link_to bar.bar_name, bar %>
</li>

app/views/bars/_form.html.erb
<%=form_for(@bar) do |f| %>
<% if @bar.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@bar.errors.count, "error") %> prohibit this bar from being saved: </h2>
  <ul>
    <% @bar.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>

</div>
<% end %>

  <div class="field">
    <%= f.label :bar_name %><br>
    <%= f.text_field :bar_name %>
  </div>

  <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
  </div>

  <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
  </div>

  <div class="field">
      <%= f.label :zipcode %><br>
      <%= f.text_field :zipcode %>
  </div>

  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.text_field :neighborhood %>
  </div>

  <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
  </div>

  <div class="field">
      <%= f.label :website %><br>
      <%= f.text_field :website %>
  </div>

  <h3>Specials</h3>
  <%= f.fields_for :specials do |s| %>
  <div class="Specials_fields">
    <div class="field">
      <%= s.label :special_description %>
      <%= s.text_field :special_description, class: 'form-control' %>
    </div>

    <div class="field">
      <%= s.label :day %>
      <%= s.text_field :day, class: 'form-control' %>
      </div>

    <div class="field">
      <%= s.label :special_price %>
      <%= s.text_field :special_price, class: 'form-control' %>
    </div>

    <div class="field">
      <%= s.label :start_time %>
      <%= s.time_field :start_time, class: 'form-control' %>
    </div>

    <div class="field">
      <%= s.label :end_time %>
      <%= s.time_field :end_time, class: 'form-control' %>
    </div>
  </div>

    <% end %>

    <div class="actions">
      <%= f.submit%>
    </div>

    <% end %>

app/views/bars/destroy.html.erb
<h1>Bars#destroy</h1>
<p>Find me in app/views/bars/destroy.html.erb</p>

app/views/bars/edit.html.erb
<% provide(:title, "Edit Bar") %>
<h1>Edit Pau Hana Bar Listing  </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for edit_bar_path(@bar) do |f| %>

      <%= f.label :bar_name %>
      <%= f.text_field :bar_name, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: 'form-control' %>

      <%= f.label :neighborhood %>
      <%= f.text_field :neighborhood, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>

      <h2>Specials</h2>
      <%= f.fields_for :specials do |s| %>
      <div class="Specials_fields">
        <div class="field">
          <%= s.label :special_description %>
          <%= s.text_field :special_description, class: 'form-control' %>
        </div>

        <div class="field">
          <%= s.label :day %>
          <%= s.text_field :day, class: 'form-control' %>
          </div>

        <div class="field">
          <%= s.label :special_price %>
          <%= s.text_field :special_price, class: 'form-control' %>
        </div>

        <div class="field">
          <%= s.label :start_time %>
          <%= s.time_field :start_time, class: 'form-control' %>
        </div>

        <div class="field">
          <%= s.label :end_time %>
          <%= s.time_field :end_time, class: 'form-control' %>
        </div>
      </div>

        <% end %>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/bars/index.html.erb
<% provide(:title, 'Pau Hana Bars') %>
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<h1>Pau Hana Bars Nearby</h1>


<div style='width: 800px;'>
<div id="multi_markers" style='width: 800px; height: 400px;'></div>
</div>
  <script type="text/javascript">



  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
    var markers = handler.addMarkers(<%=raw @hash.to_json %>)
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });


  </script>
</div>



<%= will_paginate %>
<ul class="bars">
    <%= render @bars %>
</ul>
<%= will_paginate %>



  </div>
</div>

app/views/bars/new.html.erb
<% provide(:title, 'New Bar') %>
<h1>New Pau Hana Chi Bar</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for @bar do |f| %>

      <%= f.label :bar_name %>
      <%= f.text_field :bar_name, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: 'form-control' %>

      <%= f.label :neighborhood %>
      <%= f.text_field :neighborhood, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>

      <h2>Specials</h2>

      <%= f.fields_for :specials do |s| %>

          <%= s.label :special_description %>
          <%= s.text_field :special_description, class: 'form-control' %>

          <%= s.label :day %>
          <%= s.text_field :day, class: 'form-control' %>

          <%= s.label :special_price %>
          <%= s.text_field :special_price, class: 'form-control' %>

          <%= s.label :start_time %>
          <%= s.time_field :start_time, class: 'form-control' %>

          <%= s.label :end_time %>
          <%= s.time_field :end_time, class: 'form-control' %>



        <% end %>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>

app/views/bars/oldindex.html.erb
<% provide(:title, 'Bars') %>

<h1>Bars</h1>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC-eEGhus9zRE4SpPYdnsA5bA1enVe790k&sensor=false"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/src/geolocationmarker-compiled.js"></script>
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script type="text/javascript">

//Map
var map, GeoMarker;

function initialize() {
  var markers = [];

  //init googlemap
  var mapOptions = {
    zoom: 16,
      center: new google.maps.LatLng(41.8905541,-87.629036),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      panControl: false,
      mapTypeControl: false,
      streetViewControl: false,
      zoomControl: false
  };
  map = new google.maps.Map(document.getElementById('bar_map'),
        mapOptions);

  // get users location and center the map on it
  GeoMarker = new GeolocationMarker();
  GeoMarker.setCircleOptions({visible: false});
  // center map on location
  google.maps.event.addListenerOnce(GeoMarker, 'position_changed', function() {
  map.setCenter(this.getPosition());
  });

  google.maps.event.addListener(GeoMarker, 'geolocation_error', function(e) {
    alert('There was an error obtaining your position. Message: ' + e.message);
  });

  GeoMarker.setMap(map);

  //create the marker for each location and put it in the db




  <% @bars.each do |bar| %>

   var infowindow = new google.maps.InfoWindow()

    marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%= bar.latitude %>, <%= bar.longitude %>),
      map: map,
      icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
    });

    google.maps.event.addListener(marker, 'click', (function(marker) {
      return function() {
        infowindow.setContent(
          '<div id="windowInfo">'+
          '<%= link_to (bar_path(bar.id)) do %>' +
              '<p><%= bar.bar_name %></p>' +
              '<p><%= bar.address %></p>' +
              '</p><%= bar.phone %></p>' +
          '<% end %>' +
          '</div>'
        );
          infowindow.open(map, marker);
      }
    }) (marker));
  <% end %>

  // create search box
    var data = (document.getElementById('pac-input'));
    var searchBox = new google.maps.places.SearchBox((data));

    // [START region_getplaces]
    // Listen for the event fired when the user selects an item from the
    // pick list. Retrieve the matching places for that item.
    google.maps.event.addListener(searchBox, 'places_changed', function() {
      var places = searchBox.getPlaces();

      for (var i = 0, marker; marker = markers[i]; i++) {
        marker.setMap(null);
      }

      // For each place, get the icon, place name, and location.
      markers = [];
      var bounds = new google.maps.LatLngBounds();
      for (var i = 0, place; place = places[i]; i++) {
        var image = {
          url: place.icon,
          size: new google.maps.Size(71, 71),
          origin: new google.maps.Point(0, 0),
          anchor: new google.maps.Point(17, 34),
          scaledSize: new google.maps.Size(25, 25)
        };

        // Create a marker for each place.
        var marker = new google.maps.Marker({
          map: map,
          icon: image,
          title: place.name,
          position: place.geometry.location
        });

        markers.push(marker);

        bounds.extend(place.geometry.location);
      }

      map.fitBounds(bounds);
    });

    // bias search results towards places that are within the bounds of the current map's viewport.
    google.maps.event.addListener(map, 'bounds_changed', function() {
      var bounds = map.getBounds();
      searchBox.setBounds(bounds);
    });

} //end initialize

google.maps.event.addDomListener(window, 'load', initialize);

if(!navigator.geolocation) {
  alert('Your browser does not support geolocation');
}

// switching between list and map
function show_map(){
document.getElementById("bar_list").style.display = "none";
document.getElementById("bar_map").style.display = "block";
document.getElementById("pac-input").style.display = "block";
var list = document.getElementById("List");
  list.style.boxShadow = "none";
  list.style.mozBoxShadow = "none";
  list.style.webkitBoxShadow = "none";
  list.style.border = "none";
  list.style.color = "rgb(61, 71, 81)";
var map = document.getElementById("Map");
  map.style.boxShadow = "0px 3px 5px #323232";
  map.style.mozBoxShadow = "0px 3px 5px #323232";
  map.style.webkitBoxShadow = "0px 3px 5px #323232";
  map.style.color = "rgb(232, 215, 215)";
}

function show_list(){
document.getElementById("bar_list").style.display = "none";
document.getElementById("bar_list").style.display = "block";
document.getElementById("pac-input").style.display = "none";
var map = document.getElementById("Map");
  map.style.boxShadow = "none";
  map.style.mozBoxShadow = "none";
  map.style.webkitBoxShadow = "none";
  map.style.border = "none";
  map.style.color = "rgb(61, 71, 81)";
var list = document.getElementById("List");
  list.style.boxShadow = "0px 3px 5px #323232";
  list.style.mozBoxShadow = "0px 3px 5px #323232";
  list.style.webkitBoxShadow = "0px 3px 5px #323232";
  list.style.color = "rgb(232, 215, 215)";
}
</script>

<% end %>

<div id="bar_index_container">
  <div id="bar_nav">
    <div class="bar_nav_buttons">
      <button type="button" name="List" id="List" class ="bar_index_button" OnClick="show_list();">list</button>
    </div>
    <div class="bar_nav_buttons">
      <button type="button" name="Map" id="Map" class ="bar_index_button" OnClick="show_map();">map</button>
    </div>
    <input id="pac-input" class="controls" type="text" placeholder="Where do you want to Pau Hana Today?">
  </div>

  <div id="bar_map">
  </div>

  <div id="bar_list">
    <ul>
      <% @bars.each do |bar| %>
        <li class="bar_tile">
          <%= link_to (bar_path(bar.id)) do %>
          <!-- <div class="bar_picture">
              <%= image_tag loc.thumbnail.url, class: 'loc_thumbnail' %>
            </div> -->
            <div class="bar_contact">
                <ul>
                  <li class="bar_name"><%= bar.bar_name %></li>
                  <li class="bar_address"><%= bar.address %></li>
                  <li class="bar_phone"><%= bar.phone %></li>
                  <li class="bar_mi"><%= bar.distance_to([41.8905541,-87.629036]).round(1) %> mi</li>
                </ul>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/bars/show.html.erb
<% provide(:title, @bar.bar_name) %>

<div class="row">

    <section class="bar_info" >
<h5>


        <br><%= @bar.bar_name %></br>
        <br><%= @bar.address %></br>
        <br><%= @bar.city %></br>
        <br><%= @bar.zipcode %></br>
        <br><%= @bar.neighborhood %></br>
        <br><%= @bar.phone %></br>
        <br><%= @bar.website %></br>
        <br><%= render @specials %></br>


</h5>



<% if current_user.admin?  %>

   <%= link_to "Delete", @bar, method: :delete, class: "btn btn-primary",
                                data: { confirm: "You sure?" } %>
    <%= link_to "Edit", @current_bar, method: :edit, class: "btn btn-danger" %>
<% end %>





    </section>

</div>