config/routes.rb
Rails.application.routes.draw do

resources :sessions, only: [:new, :index, :destroy]

resources :users #, only: [:new, :index, :create, :show]

root "home#index"

resources :specials, :bars, :users

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'bars/new' => 'bars#new'
  resources :bars do
    resources :specials
  end

get '/bars/:bar_id/specials/:id' => 'specials#show'
get '/bars/:bar_id/specials' => 'specials#create'

  get 'bars/index'

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_many :specials

  accepts_nested_attributes_for :specials,
  :allow_destroy => true,
  :reject_if => :all_blank

  geocoded_by :address
  after_validation :geocode 
end

app/models/special.rb
class Special < ActiveRecord::Base
  belongs_to :bar
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  validates :user_name, presence: true, length: {maximum: 50},
                      uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 3 }, allow_nil: true

# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  #simple coding by ip_address > http://www.rubygeocoder.com/
  geocoded_by :ip_address,
  :latitude => :lat, :longitude => :lon
after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
      redirect_to login
    end
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :set_bar, only: [:show, :edit, :update]
  before_action :admin_user,     only: :destroy

  # get/bars
  def index
    @bars = Bar.paginate(page: params[:page])
    @hash = Gmaps4rails.build_markers(@bars) do |bar, marker|
      marker.lat bar.latitude
      marker.lng bar.longitude
      marker.infowindow bar.bar_name
      marker.picture( {
        "url": "http://i.imgur.com/dNVi4Xq.png",
        "width":  32,
        "height": 32})
    end
  end

# post/bars
  def create
    @bar = Bar.new bar_params
    if @bar.save
      flash[:success] = ('Bar was added to Pau Hana Chi!')
      redirect_to bars_path
      else
        render :new
    end
  end

  # get/bar/new
  def new
    @bar = Bar.new
    3.times { @bar.specials.build}
  end

  # get/bars/id/edit
  def edit
    @bar = current_bar
  end

  # get/bars/id
  def show
    @bar = Bar.find(params[:id])
    @specials = current_bar.specials
  end

# patch/put/bars/1
  def update
    @bar = current_bar
    @specials =current_bar.specials
    if @bar.update_attributes(bar_params)


      flash[:success] = "Bar updated"
      redirect_to @bar
    else
      render 'edit'
  end
end
# delete/bars/id
  def destroy
    @bar = current_bar
    @bar.destroy
    flash[:success] = "Bar Deleted"
    redirect_to bars_path
  end

#bars latitude and longitude
  def bar_lat_long
    @barslatlong = [params[:latitude],params[:longitude]].join(",")
  end




private

  def set_bar
    @bar = Bar.find(params[:id])
  end

  def current_bar
    @current_bar || Bar.find(params[:id]) if params[:id]
  end

  def bar_params
    params.require(:bar).permit(:bar_name, :address, :city, :zipcode, :neighborhood, :phone, :website, :latitude, :longitude, specials_attributes:[:special_id, :special_description, :day, :special_price, :start_time, :end_time])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end #the real end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect to the user's show page.
        log_in user
        redirect_to root_url
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
  end

  def destroy
      log_out
      flash[:success] = "Come back soon!"
      redirect_to root_url
  end

end #the real end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController

before_action :admin_user,     only: [:destroy, :edit]
#get/specials
  def index
    @specials = Special.all
  end
# post/Specials
  def create
    @bar = Bar.find(params[:bar_id])
    @special = @bar.specials.build

    if @special.save
      flash[:success] = ["Special was added "]
      redirect_to bar_path
        else
        render :new
      end
    end

#get/special/new
  def new
    @bar = Bar.find(params[:bar_id])
    @special = @bar.specials.build
  end

  def edit
    @special = current_special
  end

  def show

    @special = current_special

  end

  def update
    @special =current_special
    if @special.update_attributes(params[:special])
      flash[:success] = "Special Updated"
      redirect_to @bar
    else
      render 'edit'
  end
end

  def destroy
    @special_price = current_special
    @special.destroy
    flash[:success] = "Special deleted"
    redirect_to bar_path
  end


private


  def current_special
    @current_special || Special.find(params[:id]) if params[:id]

  end

  def special_params
    params.require(:special).permit(:special_description, :day, :special_price, :start_time, :end_time)

  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end # the real end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Pau Hana Chi"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
      session.delete(:user_id)
      @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  Pau Hana Chi  &copy 2016
  </small>
  <nav>
    <ul>
      <%= link_to "",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"id="navcolor">
  <div class="container">
    <%= link_to "PAU HANA CHI", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if logged_in? && current_user.admin? %>
          <li><%= link_to "Specials", bars_path %></li>
          <li><%= link_to "Add Bar Special", bars_new_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Admin Controls <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Users", users_path %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% end %>
        <!-- begin Navbar for logged in user thats not admin-->
        <% if logged_in? && !current_user.admin? %>
          <li><%= link_to "Add Bar Special", bars_new_path %></li>
          <li><%= link_to "Specials", bars_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul></li>
          <% end %>
          <% if !logged_in? %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

      <%= yield %>
      
    <%= render 'layouts/footer' %>
    <!-- <%= debug(params) if Rails.env.development? %> -->

    </div>

  </body>
</html>